export const FETCH_COLLECTINOS_START = 'FETCH_COLLECTINOS_START';
export const FETCH_COLLECTINOS_SUCCESS = 'FETCH_COLLECTINOS_SUCCESS';
export const FETCH_COLLECTINOS_FAILURE = 'FETCH_COLLECTINOS_FAILURE';
